# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/translucid',
                'doc_host': 'https://ssslakter.github.io',
                'git_url': 'https://github.com/ssslakter/translucid',
                'lib_path': 'translucid'},
  'syms': { 'translucid.opt': { 'translucid.opt.Hook': ('opt.html#hook', 'translucid/opt.py'),
                                'translucid.opt.Hook.__del__': ('opt.html#hook.__del__', 'translucid/opt.py'),
                                'translucid.opt.Hook.__init__': ('opt.html#hook.__init__', 'translucid/opt.py'),
                                'translucid.opt.Hook.remove': ('opt.html#hook.remove', 'translucid/opt.py'),
                                'translucid.opt.Hooks': ('opt.html#hooks', 'translucid/opt.py'),
                                'translucid.opt.Hooks.__del__': ('opt.html#hooks.__del__', 'translucid/opt.py'),
                                'translucid.opt.Hooks.__delitem__': ('opt.html#hooks.__delitem__', 'translucid/opt.py'),
                                'translucid.opt.Hooks.__enter__': ('opt.html#hooks.__enter__', 'translucid/opt.py'),
                                'translucid.opt.Hooks.__exit__': ('opt.html#hooks.__exit__', 'translucid/opt.py'),
                                'translucid.opt.Hooks.__init__': ('opt.html#hooks.__init__', 'translucid/opt.py'),
                                'translucid.opt.Hooks.remove': ('opt.html#hooks.remove', 'translucid/opt.py')}}}
