# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_opt.ipynb.

# %% auto 0
__all__ = ['to_cpu']

# %% ../nbs/03_opt.ipynb 2
def to_cpu(x):
    if isinstance(x, (list, tuple)):
        return [to_cpu(o) for o in x]
    return x.detach().cpu()
