# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/opt.ipynb.

# %% auto 0
__all__ = ['Hook', 'Hooks', 'CancelFitException']

# %% ../nbs/opt.ipynb 1
import torch
from torch.utils.data import DataLoader
from torch import nn, optim
from fastcore.all import *
from pathlib import Path
import torch.nn.functional as F
from fastprogress import master_bar, progress_bar
from fastprogress import progress_bar

# %% ../nbs/opt.ipynb 7
class Hook:
    def __init__(self, module, hook, when='forward'): 
        attr = f'register_full_{when}_hook' if 'back' in when else f'register_{when}_hook'
        self.hook = getattr(module, attr)(hook)
    def remove(self): self.hook.remove()
    def __del__(self): self.remove()

class Hooks(list):
    def __init__(self, *ms, fn, when='forward'): super().__init__([Hook(m, fn, when) for m in ms])
    def __delitem__(self, i): 
        self[i].remove()
        del super()[i]
    def remove(self): 
        for h in self: h.remove()
    def __del__(self): self.remove()
    def __enter__(self): return self
    def __exit__(self, *_): self.remove()

# %% ../nbs/opt.ipynb 9
class CancelFitException(Exception): pass
